### ISSUE TITLE
Development planning, Milestone 3

### ISSUE THREAD

**Issue by mike-lischke** [mike-lischke/antlr-ng#10]
This list covers the next steps after having both a full TS runtime and the full runtime/api tests ported to TS.

- [x] Consolidate the TS runtime (consistent naming of properties, remove leading underscores in properties, really make private what is private, convert data-only classes to interfaces etc.).
- [x] Optimize the runtime to get it as close as possible to the old JS runtime execution speed.
- [x] Do initial port of the Java ANTLR4 tool to TS and make it build.
- [x] Port all tool tests to TS and make them run successfully.
- [x] Create an entry point to allow running antlr-ng like the old jar.
- [x] Generate all files for certain grammars, for all supported target languages with both, antlr-ng and antlr4 and compare the output. There must be no significant difference.
    - [x] Java
    - [x] MySQL
- [x] Clean everything up and fix bugs.
- [x] Complete package build and add binary commands:
    - [x] Tool
    - [x] Test rig (grun)
    - [x] Interpreter
- [x] Do beta releases of the tool as node package.
- [x] Make the tool bootstrap itself. 
- [x] Setup the initial web page for the project
- [x] Do the 1.0 release.

The first two steps are handled in an own branch, which later gets released as a new major version (because of API changes).

**Comment by mike-lischke** [comment]
🎉 The optimized antlr4ng runtime performs really well. It's faster in most aspects than any of the other TS/JS runtimes (antlr4, antlr4ts, antlr4wasm).

**Comment by mike-lischke** [comment]
Getting closer to finish the next step - only ~3500 errors left. They are exclusively in the most challenging parts of the tool: the tree walkers. These are generated from ANTLR3 tree grammars and will be rewritten to avoid the need of ANTLR3. No (re) generation possible after this point, but we finally get rid of ANTLR3 entirely.

**Comment by mike-lischke** [comment]
🥳 All syntax errors fixed.

**Comment by mike-lischke** [comment]
Lots of progress meanwhile:

- Grammar parsing works. A conversion of the parse tree to an AST has been introduced, which eases many tasks.
- Tree walkers mostly do their job. One old ANTLR3 prediction is left and needs a fix.
- Semantic pipeline working (inclusive left recursion removal).

**Comment by mike-lischke** [comment]
A large part of code generation works now (see b3d8cc68b181e40fddee1cff1d8f327b1638e8e1). A couple of things need fixes (ATN generation, rule/token names, things like that), but we are getting closer.

**Comment by mike-lischke** [comment]
Didn't expect that working on ANTLRng would show such an amount of runtime problems in antlr4ng and stringtemplate4ts, which lead to the stream of minor releases lately.

**Comment by mike-lischke** [comment]
All tests are done and run successfully now, so I'd say we have a working TypeScript port of the ANTLR4 tool! Next step (besides cleanup) will be to generate a number of parsers/lexers from large grammars, once with antlr4ng and once with the antlr4 jar, and compare the generated code.

@kaby76  I'm eager to hear your suggestions for the best approach to use - difficult grammars that use as many of ANTLR4's feature as possible, in any of the supported languages).

**Comment by kaby76** [comment]
Fabulous!! Will think about it. And will give it a try.

**Comment by kaby76** [comment]
I might not be up to date, but I'm getting this on "main".
```
ken@DESKTOP-DL44R7B:~/ANTLRng$ tsc -p tsconfig.json
src/antlr3/BaseRecognizer.ts:374:28 - error TS2531: Object is possibly 'null'.

374         const stopIndexI = this.state.ruleMemo![ruleIndex].get(ruleStartIndex);
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/antlr3/BaseRecognizer.ts:424:13 - error TS2531: Object is possibly 'null'.

424             this.state.ruleMemo![ruleIndex].set(ruleStartIndex, stopTokenIndex);
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/tool/Grammar.ts:789:13 - error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

789             return this.typeToStringLiteralList[ttype];
                ~~~~~~

src/tool/Grammar.ts:793:13 - error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

793             return this.typeToTokenList[ttype];
                ~~~~~~

src/tool/ast/GrammarRootAST.ts:100:13 - error TS2322: Type 'unknown' is not assignable to type 'string | undefined'.

100             return this.toolParameters[key];
                ~~~~~~


Found 5 errors in 3 files.

Errors  Files
     2  src/antlr3/BaseRecognizer.ts:374
     2  src/tool/Grammar.ts:789
     1  src/tool/ast/GrammarRootAST.ts:100
ken@DESKTOP-DL44R7B:~/ANTLRng$ node --version
v16.13.0
ken@DESKTOP-DL44R7B:~/ANTLRng$ tsc --version
Version 5.3.3
ken@DESKTOP-DL44R7B:~/ANTLRng$
```
For bootstrapping, I did `alias antlr4ng='java -jar ./node_modules/antlr4ng-cli/antlr4-4.13.2-SNAPSHOT-complete.jar -Dlanguage=TypeScript'` in my `.profile` (Ubuntu) and invoked with `base -i` to run the tool.

**Comment by mike-lischke** [comment]
You are quick @kaby76 :-) I'm currently working to provide something to run the tool and debug it. I have pushed another patch to address the issues in BaseRecognizer.ts

**Comment by mike-lischke** [comment]
Another push later you can use the TS tool. Make sure you update the node packages (`npm i` in the project root). Then run:

```shell
npx tsx cli/runner.ts -Dlanguage=CSharp --exact-output-dir --generate-visitor -o temp tests/grammars/Java.g4
```

... you know the parameters. The output parameter is currently being ignored. Need to fix that yet. If you get an error about `npx` install it using `npm install -g npx`.

**Comment by mike-lischke** [comment]
I found a number of differences while comparing the generated files (from the jar and antlr-ng) and fixed them all in the last patch. Time to set up a script that generates the files for all grammars in the grammar directory and compare them.

**Comment by mike-lischke** [comment]
From here it looks like all common/major problems have been addressed. Generated files differ only in insignificant parts from those generated with the old ANTLR jar, that is, the file names that appear in the output (if the used grammar is located in a different folder) and the order of generated visitor/listener methods, as well as parser contexts for alts with an alt label. The latter has no functional impact. It's just that antlr-ng writes out these elements in the order they appear in the grammar, while old ANLTR seems to have a rather random order.

**Comment by kaby76** [comment]
I've added the two remaining bugs of the `antlr-ng tool with antlr4ng runtime` testing. All parse trees between the new tool and the old "java -jar" tool are identical except for these two parse bugs, of course.

The [eiffel grammar](https://github.com/antlr/grammars-v4/tree/7f917add1199e8b050a7117814899ebab50a3c3b/eiffel) does not work with the other ports, including Antlr4ng. [The only target listed is Java](https://github.com/antlr/grammars-v4/blob/7f917add1199e8b050a7117814899ebab50a3c3b/eiffel/desc.xml#L4). The reason why we don't just blanket test everything is because people sometimes embedded target-specific code in actions, which is why the eiffel grammar isn't tested with antlr-ng. The assumption is: "Why test the tool if you can't actually do a build and/or a parse?" That was probably too restrictive. But, if antlr-ng really works with the other ports, the error will probably, eventually get caught.

The plan is to continue testing the new antlr-ng tool with the other runtimes. Trash is written in C#. I would also like to test the parses with the "trace" feature. That technique goes one level down further to verify that the config sets are correct. I do plan on adding the antlr-ng tool and antlr4ng pair to the builds for grammars-v4.

**Comment by kaby76** [comment]
Mike, Is it possible to get a point release of antlr-ng into npmjs.com? Antlr-ng seems pretty solid, and I'd like to be able to run the new tool in a GitHub Action for a branch in grammars-v4 across all targets, all OSes. --Ken

**Comment by mike-lischke** [comment]
Hmm, I wanted everything to clean up first, migrate or remove old ANTLR3 stuff that's still in the tool etc. Also at least some documentation is necessary. Let me think about it.

**Comment by mike-lischke** [comment]
The first public release: https://www.npmjs.com/package/antlr-ng 🎉

However, I'll stick to my plan and consider it published not before cleaning up everything and have its web site ready.

**Comment by mike-lischke** [comment]
Eat your own dog food! The tool now uses itself to build needed parsers for its build and testing (the previous version of the tool is used for that).

**Comment by kaby76** [comment]
The plan over in grammars-v4 is integrate the new tool along side the old tool in the builds. I'll need to update the test generator to generate drivers that use different tools, as well as targets/ports. Finally, a TypeScript target with full type checking. Good work.

**Comment by mike-lischke** [comment]
Mission accomplished, version 1.0.0 is in the wild.
